### ISSUE TITLE
Retaining cookie between requests?

### ISSUE THREAD

**Issue by disintegrator** [luckymarmot/Paw-Documentation#2]
Hi,

It's not quite clear to me how to retain the cookie between requests. This is important because it the contains a session ID (`sid`) and a couple other values I need when building API tests.

Could you please explain how this is done?

Thank you.

**Comment by mittsh** [comment]
Just to update this year old ticket, Paw now has [Cookie Jars](https://luckymarmot.com/paw/doc/Cookies) for this. Here's the doc article: https://luckymarmot.com/paw/doc/Cookies
