### ISSUE TITLE
Documentation for extensions

### ISSUE THREAD

**Issue by dac09** [luckymarmot/Paw-Documentation#6]
Hi,

Is there any documentation available for creating extensions? I've looked at some of your examples, but can't seem to work out where to start.

I'm looking to create an extension (initially atleast!) for a custom auth scheme.

Thanks,
Daniel

**Comment by kwent** [comment]
Did you already read those links ?
- http://luckymarmot.com/paw/doc/Extensions/Overview
- http://luckymarmot.com/paw/doc/Extensions/Reference/Reference
- http://luckymarmot.com/paw/doc/Extensions/Create_Code_Generator_Extension

Regards

**Comment by dac09** [comment]
Didn't notice, thanks. I'll have a look :)

**Comment by dac09** [comment]
That combined with factorial stuff is pretty decent actually, I know what to do. Thanks and keep up the great work!

**Comment by kwent** [comment]
You can also check the other extensions available here : https://github.com/luckymarmot

**Comment by dac09** [comment]
Hi Kwent,

I've managed to come up with an extension based on the examples and documentation so far.

However, it seems that neither standard Node.js nor Browser modules are available to be used. How can I make an HTTP request _through_ the extension?

As I mentioned, I'm trying to configure an auth scheme to obtain a bearer token. Is there another way I can achieve this?

Thanks,
Daniel

**Comment by kwent** [comment]
@dac09 Sorry just saw that ! Well you are right. Nodejs module are not supported so far but they will be soon with the next version ! We will keep you posted !

**Comment by dac09** [comment]
Thanks - really useful. :+1:
